server:
  port: 8081

spring.devtools.livereload.enabled: false

logging:
  level:
    root: info
    web: debug

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---

spring.config.activate.on-profile: docker

