server:
  port: 8081

spring.devtools.livereload.enabled: false

network:
  user-service:
    scheme: http
    domain: localhost
    port: 8080

spring.cloud.stream:
  default-binder: kafka
#  default.contentType: application/json
  bindings:
    users-out-0:
      destination: users
      content-type: application/json
      group: usersGroup
      producer:
        required-groups: auditGroup
        partition-key-expression: headers['partitionKey']
        partition-count: 2

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

logging:
  level:
    root: info
    web: debug

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---

spring.config.activate.on-profile: docker

server:
  port: 8080

network:
  user-service:
    scheme: http
    domain: user-service
    port: 8080

spring.kafka.bootstrap-servers: kafka:9092

spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          replication-factor: 1