server:
  port: 8080

spring.devtools.livereload.enabled: false

spring:
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          replication-factor: 1
          brokers: kafka
      # In case of changing binding names, don't forget to correct corresponding values in com.formanova.integration.client classes
      bindings:
        userService-out-0:
          destination: user-service
          content-type: application/json
          group: user-service-group
          producer:
            required-groups: auditGroup
            partition-key-expression: headers['partitionKey']
            partition-count: 1
        ratingService-out-0:
          destination: rating-service
          content-type: application/json
          group: rating-service-group
          producer:
            required-groups: auditGroup
            partition-key-expression: headers['partitionKey']
            partition-count: 1

network:
  user-service:
    scheme: http
    domain: localhost
    port: 8081
  rating-service:
    scheme: http
    domain: localhost
    port: 8082

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---

spring.config.activate.on-profile: docker

network:
  user-service:
    domain: user-service
    port: 8080
  rating-service:
    domain: rating-service
    port: 8080

spring:
  kafka:
    bootstrap-servers: kafka:9092